### ISSUE TITLE
Having issue finding code samples for Merchant API

### ISSUE THREAD

**Issue by gamimgdecksarethebest** [google/merchant-api-samples#6]
I can't find the product resource code samples on here: https://developers.google.com/merchant/api/samples

Could you please help me?

**Comment by damaz91** [comment]
Hello Content API for Shopping User, 

Thank you for contacting us for support.

If you reached out to us through Github, we recommend re-submit your query directly to our [developer support](https://support.google.com/merchants/contact/shopping_api_support_form). This will allow us to better understand your needs and provide quicker solutions. 

For any queries provided through Github only, there isn’t a set time we will be able to get back to you which we will do the best we can.

Thank you,
The Merchant API Team
